### ISSUE TITLE
Installing basks instead of individual package

### ISSUE THREAD

**Issue by pauleveritt** [basscss/bassplate#10]
I realize this is likely a PostCSS question...this demo shows a package.json that depends on each Basscss individual package. I'd like to switch to just doing:

```
npm install basscss
```

But then each Basscss component is under node_modules/basscss/node_modules/*. I can't figure out the correct `@import` to use for a case like this.

I think it is worth documenting somewhere as people are more likely to use the single npm package. I don't know if this demo is the correct place or the Basscss docs themselves.

**Comment by pauleveritt** [comment]
Yikes, I didn't even look inside the basscss npm package. It only has a few of the node_modules. Closing.

**Comment by jxnblk** [comment]
I offer all the modules in this repo to make it easy to remove ones you don't need (rather than look up and add ones you do). FWIW, I think in npm v3 that module dependencies will be flattened into the root `node_modules` folder, and that might help out in the future.
