### ISSUE TITLE
bassplate on Windows, single quotes and parallel scripts

### ISSUE THREAD

**Issue by SiNNuT** [basscss/bassplate#12]
The watch:css script does not work on Windows 10 and probably all Win versions. Being quite new to node and npm it took me a while to figure out that the single quotes where the problem here. Some info here: https://github.com/keithamus/npm-scripts-example/issues/5

Using escaped double quotes solves the problem and should work on all OS's.

```
"watch:css": "watch \"npm run css && npm run minify:css\" ./src"
```

Also the parallel running with **&** in the start script does not work on Windows. Only the watch:css runs. If you change the order only serve is being run. I don't need the http-server so not a problem for me but you could mention this somewhere. Maybe Windows users should look at https://www.npmjs.com/package/npm-run-all or maybe there is another solution i'm not aware of.

**Comment by jxnblk** [comment]
I removed the watch script altogether in #14. Let me know if you have any issues with the new setup.
