### ISSUE TITLE
npm script

### ISSUE THREAD

**Issue by RickCogley** [basscss/bassplate#13]
Hello - thank you for basscss. 

I am trying to use it for my site, starting with the "bassplate" template. I like how bassplate uses npm scripts for the build tool. 

It's using cssnext to autoprefix, but looking into node_modules after installing, this module appears to be deprecated. I think it is working still, but, how could it be upgraded to a more future-proof method? 

Also, I'm wondering if you can perhaps point me in the right direction to process js files in a similar way in an npm script? 

Thank you,
Rick

**Comment by SiNNuT** [comment]
cssnext recently switched to being a postcss plugin. It's now called postcss-cssnext.
It's easy to switch, more info here http://cssnext.io/postcss/

**Comment by RickCogley** [comment]
Thanks @SiNNuT. It's likely possible to do with npm, but the npm pipelining ends up being all the typical unwieldy (to me) bash pipelining that you'd see in a shell script (since it's apparently using `sh`). I switched to gulp and that is working fine, with postcss-cssnext. 

So far, this is what I'm using, in case anyone wants to see: 

https://gist.github.com/RickCogley/cf7e5174652e73cf1059#file-gulpfile-js-L43

**Comment by RickCogley** [comment]
Also I assume the postcss-cli is what one would need to use, if in an npm script.
