### ISSUE TITLE
Build fails with v8

### ISSUE THREAD

**Issue by ropsii** [basscss/bassplate#19]
I was testing v8 with bassplate, and it fails to build. I didn't update the existing project, but did the clean install. I guess it has to do with incorrect paths after the update to v8. Here's the excerpt:

`postcss-import: /Users/petar/Dropbox/Projects/basscss8/src/base.css:20:1: Failed to find 'basscss-padding'
    in [ 
        /Users/petar/Dropbox/Projects/basscss8/src
    ]`

`postcss-import: /Users/petar/Dropbox/Projects/basscss8/src/base.css:21:1: Failed to find 'basscss-grid'
    in [ 
        /Users/petar/Dropbox/Projects/basscss8/src
    ]`

`postcss-import: /Users/petar/Dropbox/Projects/basscss8/src/base.css:22:1: Failed to find 'basscss-flexbox'
    in [ 
        /Users/petar/Dropbox/Projects/basscss8/src
    ]`

**Comment by jxnblk** [comment]
Did you try `rm -rf node_modules && npm i`?

**Comment by ropsii** [comment]
Tried it, still fails.

**Comment by jxnblk** [comment]
It's hard to say what's happening exactly...

What version of npm are you using? If you're using an older version, you may need to manually install the packages, since they might not be flattened in the `node_modules` folder.

**Comment by ropsii** [comment]
You were right, it was the npm related issue. I can confirm that after upgrading npm (2.11.3 to 3.7.2) build (of a clean install) works. Thanks.
