### ISSUE TITLE
Custom properties variables list

### ISSUE THREAD

**Issue by arianjinx** [basscss/bassplate#21]
Hello guys, thanks for creating cool toolkit such as BASSCSS 😃. I need to ask something how can I override custom properties in this package https://github.com/basscss/bassplate? I can't find where the documentation of available variables. Thank you!

**Comment by jxnblk** [comment]
You can uncomment and add custom variables here: https://github.com/basscss/bassplate/blob/master/src/base.css#L64

As for the list of available custom properties, check the source of the modules you're using. E.g. https://github.com/basscss/basscss/blob/master/modules/margin/index.css#L52-L56
