### ISSUE TITLE
@import for basscss modules not working as intended?

### ISSUE THREAD

**Issue by addisonhall** [basscss/bassplate#22]
I'll preface this by stating that I'm new to PostCSS, so this may be user error. After installing and running bassplate as instructed, the imports for standard modules such as ``@import 'basscss-typography';`` simply output themselves instead of the CSS in the corresponding file.

I've found that if I use ``@import 'basscss/node_modules/basscss-typography';`` it will work as expected.

And if it makes any difference, I'm using Node 4.4.5 on Windows.

**Comment by maoizm** [comment]
Did you run npm install / npm run css?

If so try npm uninstall or delete node_modules/* and run npm install again  — npm used to have weird dependency caching bugs (and I suggest that you upgrade Node to the latest LTS version because of this)

**Comment by addisonhall** [comment]
I did run npm to "compile" the css, but I'll try upgrading node... That will probably help me out across the board.
